### ISSUE TITLE
Product Page Info

### ISSUE THREAD

**Issue by alexhuah** [CSC307Winter2019/Group4#51]
Fix product details

**Comment by iworourke** [comment]
Goal is to make the Product Page populate itself correctly after a user clicks on a particular product in the shop.

1. When the user is in the shop and they click on the product, add the userId to the store(which exists on the client's local machine and is essentially a global variable we can use to hold onto information between pages) .

2. In the Product.Vue page, get the saved productId out of the store

3. Add a route to the middle tier that the client can call to get the information of a single product. Currently we have a method that gets the information of all the products in the table. We want to just get one of them, so well have to use the find() to specify a condition that requires the productId to match. **(test this with postman)**

4. Call the middle tier function from within the Product.vue to populate a Product object

5. Set the Product object to be the data source in the html template of Product.vue

**Comment by iworourke** [comment]
Following example for logging in a user shows that setting the desired product's information in the store can be very similar and is more straightforward.

Instead of placing the id in the store and then doing an additional query once we arrive at the Product page to set the product's information, inside the store.ts file we receive the productId use it to get the product object, and then place the entire product object in the store.

**Comment by iworourke** [comment]
Alex's implementation: 
1. making the product page's URL include the id of the product the user selected. 
2. within Product.vue, access the $route object to retrieve the product id from the URL.
3. use an axios.get() upon the url "/products/<product_id>" to call the method that queries the database for a particular product
4. In the controller for products, "product.controller.ts", create a new route at "/products/:id", create an instance of the product repository can call findOne on it while providing the id of the desired product.
